# Dates
# The max date is not included in the range
dates:
  min: 2024-06-25
  max: 2024-06-30

#Â Lines
# If you want equal probabilities set probabilities equal to {} like with the tsps
# If you don't want noise, just remove the noise_std key
lines:
  probabilities:
    '03612': 0.5
    '04161': 0.3
    '02731': 0.2
  noise_std: 0.05

# Train service providers
# If you want different probabilities explicitly set them here like with the lines
tsps:
  probabilities: {}

# Time slots
time_slots:
  probabilities:
    '1': 0.4
    '2': 0.3
    '3': 0.2
    '4': 0.1
    '5': 0.0

# Rolling stocks
# The first tsp has explicit probabilities, the second one has equal probabilities
rolling_stocks:
  probabilities:
    '1':
      '1': 0.4
      '2': 0.2
      '3': 0.2
      '4': 0.1
      '5': 0.1
    '2': {}

# Prices config
prices:
  base: 10  # Base price
  max: 150  # Max price
  distance_factor: 0.05  # Increase price with a factor of f * min_price per station in corridor
  tsp_factor:  # Defines how the TSP affects the price (multiplies each price by the factor)
      '1': 1.5  # Renfe AVE
      '2': 1.1  # Renfe AVLO
  seat_type_factor:  # Defines how the seat type affects the price (multiplies each price by the factor)
      '1': 1  # Tourist Class
      '2': 1.2 # Tourist Plus Class
      '3': 1.6  # Business Class
      '4': 1.8  # First Class
