# Dates
# The max date is not included in the range
dates:
  min: 2024-06-25
  max: 2024-06-26

#Â Lines
# If you want equal probabilities set probabilities equal to {} like with the tsps
# If you don't want noise, just remove the noise_std key
lines:
  probabilities:
    '03131': 0.35
    '02561': 0.15
    '06305': 0.15
    '03162': 0.35
  noise_std: 0.05

# Train service providers
# If you want different probabilities explicitly set them here like with the lines
tsps:
  probabilities: {}

# Time slots
time_slots:
  probabilities:
    - id: 1
      distribution: hourly
      distribution_kwargs:
        '0': 0
        '1': 0
        '2': 0
        '3': 0
        '4': 0
        '5': 0.02
        '6': 0.06
        '7': 0.08
        '8': 0.10
        '9': 0.06
        '10': 0.04
        '11': 0.04
        '12': 0.03
        '13': 0.03
        '14': 0.05
        '15': 0.07
        '16': 0.05
        '17': 0.08
        '18': 0.10
        '19': 0.08
        '20': 0.05
        '21': 0.03
        '22': 0.02
        '23': 0.01
    - id: 2
      distribution: poisson
      distribution_kwargs:
        mu: 14
  days:
    'Monday': 1
    'Tuesday': 1
    'Wednesday': 1
    'Thursday': 1
    'Friday': 1
    'Saturday': 2
    'Sunday': 2

# Rolling stocks
# The first tsp has explicit probabilities, the second one has equal probabilities
rolling_stocks:
  probabilities:
    '1':
      '1': 0.4
      '2': 0.2
      '3': 0.2
      '4': 0.1
      '5': 0.1
    '2': {}

# Prices config
prices:
  base: 10  # Base price
  min: 7 # Min price
  max: 150  # Max price
  distance_factor: 0.05  # Increase price with a factor of f * min_price per station in corridor
  tsp_factor:  # Defines how the TSP affects the price (multiplies each price by the factor)
      '1': 1.5  # Renfe AVE
      '2': 1.1  # Renfe AVLO
  seat_type_factor:  # Defines how the seat type affects the price (multiplies each price by the factor)
      '1': 1  # Tourist Class
      '2': 1.2 # Tourist Plus Class
      '3': 1.6  # Business Class
      '4': 1.8  # First Class
