# Dates
dates:
  min: 2024-06-25
  max: 2024-06-26

#Â Lines
lines:
  probabilities:
    '06301': 0.5
    '03073': 0.3
    '03083': 0.2

# Train service providers
tsps:
  probabilities:
    '1': 0.7
    '2': 0.3

# Time slots
time_slots:
  probabilities:
    '1': 0.4
    '2': 0.3
    '3': 0.2
    '4': 0.1
    '5': 0.0

# Rolling stocks
rolling_stocks:
  probabilities:
    '1':
      '1': 1.0
      '2': 0.0
      '3': 0.0
      '4': 0.0
      '5': 0.0
    '2':
      '1': 1.0
      '2': 0.0
      '3': 0.0
      '4': 0.0
      '5': 0.0

# Prices config
prices:
  base: 10  # Base price
  max: 150  # Max price
  distance_factor: 0.05  # Increase price with a factor of f * min_price per station in corridor
  tsp_factor:  # Defines how the TSP affects the price (multiplies each price by the factor)
      '1': 1.5  # Renfe AVE
      '2': 1.1  # Renfe AVLO
  seat_type_factor:  # Defines how the seat type affects the price (multiplies each price by the factor)
      '1': 1  # Tourist Class
      '2': 1.2 # Tourist Plus Class
      '3': 1.6  # Business Class
