# Corridors config

# Lines config
lines:
  probabilities:
    '03612': 0.5
    '04161': 0.3
    '02731': 0.2

time_slots:
  probabilities:
      1: 0.01
      2: 0.01
      3: 0.01
      4: 0.01
      5: 0.02
      6: 0.04
      7: 0.05
      8: 0.06
      9: 0.06
      10: 0.05
      11: 0.04
      12: 0.05
      13: 0.06
      14: 0.06
      15: 0.06
      16: 0.06
      17: 0.06
      18: 0.06
      19: 0.06
      20: 0.06
      21: 0.05
      22: 0.03
      23: 0.02

# Prices config
prices:
  base: 10  # Base price
  max: 150  # Max price
  distance_factor: 0.05  # Increase price with a factor of f * min_price per station in corridor
  tsp_factor:  # Defines how the TSP affects the price (multiplies each price by the factor)
      '1': 1.5  # Renfe AVE
      '2': 1.1  # Renfe AVLO
      '3': 1  # Ouigo
      '4': 0.9  # Iryo
  seat_type_factor:  # Defines how the seat type affects the price (multiplies each price by the factor)
      '1': 1  # Tourist Class
      '2': 1.2 # Tourist Plus Class
      '3': 1.6  # Business Class

# Service config
services:
  dates: # Set range for random dates
    min: 2024-06-25
    max: 2024-06-26
