market:
- id: 1
  departure_station: '60000'
  arrival_station: '71801'
- id: 2
  departure_station: '60000'
  arrival_station: '04040'
- id: 3
  departure_station: '04040'
  arrival_station: '71801'
- id: 4
  departure_station: '60000'
  arrival_station: '04104'
- id: 5
  departure_station: '04040'
  arrival_station: '04104'
- id: 6
  departure_station: '04104'
  arrival_station: '71801'
userPattern:
- id: 1
  name: Business1
  arrival_time: norm
  arrival_time_kwargs:
    loc: 8
    scale: null
  purchase_day: poisson
  purchase_day_kwargs:
    mu: 1.25
  forbidden_departure_hours:
    start: 0
    end: 4
  seats:
  - id: 1
    utility: null
  - id: 2
    utility: null
  - id: 3
    utility: null
  - id: 4
    utility: null
  - id: 5
    utility: null
  - id: 6
    utility: null
  - id: 7
    utility: null
  - id: 8
    utility: null
  - id: 9
    utility: null
  train_service_providers:
  - id: 1
    utility: null
  - id: 2
    utility: null
  - id: 3
    utility: null
  penalty_arrival_time: polynomial
  penalty_arrival_time_kwargs:
    b_0: 0
    b_1: null
  penalty_departure_time: polynomial
  penalty_departure_time_kwargs:
    b_0: 0
    b_1: null
  penalty_cost: polynomial
  penalty_cost_kwargs:
    b_0: 0
    b_1: null
  penalty_travel_time: polynomial
  penalty_travel_time_kwargs:
    b_0: 0
    b_1: null
  error: null
  error_kwargs: null
- id: 2
  name: Business2
  arrival_time: norm
  arrival_time_kwargs:
    loc: 17
    scale: null
  purchase_day: poisson
  purchase_day_kwargs:
    mu: 1.25
  forbidden_departure_hours:
    start: 0
    end: 4
  seats:
  - id: 1
    utility: null
  - id: 2
    utility: null
  - id: 3
    utility: null
  - id: 4
    utility: null
  - id: 5
    utility: null
  - id: 6
    utility: null
  - id: 7
    utility: null
  - id: 8
    utility: null
  - id: 9
    utility: null
  train_service_providers:
  - id: 1
    utility: null
  - id: 2
    utility: null
  - id: 3
    utility: null
  penalty_arrival_time: polynomial
  penalty_arrival_time_kwargs:
    b_0: 0
    b_1: null
  penalty_departure_time: polynomial
  penalty_departure_time_kwargs:
    b_0: 0
    b_1: null
  penalty_cost: polynomial
  penalty_cost_kwargs:
    b_0: 0
    b_1: null
  penalty_travel_time: polynomial
  penalty_travel_time_kwargs:
    b_0: 0
    b_1: null
  error: null
  error_kwargs: null
- id: 3
  name: Student1
  arrival_time: norm
  arrival_time_kwargs:
    loc: 8
    scale: null
  purchase_day: poisson
  purchase_day_kwargs:
    mu: 1
  forbidden_departure_hours:
    start: 0
    end: 4
  seats:
  - id: 1
    utility: null
  - id: 2
    utility: null
  - id: 3
    utility: null
  - id: 4
    utility: null
  - id: 5
    utility: null
  - id: 6
    utility: null
  - id: 7
    utility: null
  - id: 8
    utility: null
  - id: 9
    utility: null
  train_service_providers:
  - id: 1
    utility: null
  - id: 2
    utility: null
  - id: 3
    utility: null
  penalty_arrival_time: polynomial
  penalty_arrival_time_kwargs:
    b_0: 0
    b_1: null
  penalty_departure_time: polynomial
  penalty_departure_time_kwargs:
    b_0: 0
    b_1: null
  penalty_cost: polynomial
  penalty_cost_kwargs:
    b_0: 0
    b_1: null
  penalty_travel_time: polynomial
  penalty_travel_time_kwargs:
    b_0: 0
    b_1: null
  error: norm
  error_kwargs: null
- id: 4
  name: Student2
  arrival_time: norm
  arrival_time_kwargs:
    loc: 17
    scale: null
  purchase_day: poisson
  purchase_day_kwargs:
    mu: 1
  forbidden_departure_hours:
    start: 0
    end: 4
  seats:
  - id: 1
    utility: null
  - id: 2
    utility: null
  - id: 3
    utility: null
  - id: 4
    utility: null
  - id: 5
    utility: null
  - id: 6
    utility: null
  - id: 7
    utility: null
  - id: 8
    utility: null
  - id: 9
    utility: null
  train_service_providers:
  - id: 1
    utility: null
  - id: 2
    utility: null
  - id: 3
    utility: null
  penalty_arrival_time: polynomial
  penalty_arrival_time_kwargs:
    b_0: 0
    b_1: null
  penalty_departure_time: polynomial
  penalty_departure_time_kwargs:
    b_0: 0
    b_1: null
  penalty_cost: polynomial
  penalty_cost_kwargs:
    b_0: 0
    b_1: null
  penalty_travel_time: polynomial
  penalty_travel_time_kwargs:
    b_0: 0
    b_1: null
  error: norm
  error_kwargs: null
- id: 5
  name: Leisure1
  arrival_time: norm
  arrival_time_kwargs:
    loc: 8
    scale: null
  purchase_day: poisson
  purchase_day_kwargs:
    mu: 7
  forbidden_departure_hours:
    start: 0
    end: 4
  seats:
  - id: 1
    utility: null
  - id: 2
    utility: null
  - id: 3
    utility: null
  - id: 4
    utility: null
  - id: 5
    utility: null
  - id: 6
    utility: null
  - id: 7
    utility: null
  - id: 8
    utility: null
  - id: 9
    utility: null
  train_service_providers:
  - id: 1
    utility: null
  - id: 2
    utility: null
  - id: 3
    utility: null
  penalty_arrival_time: polynomial
  penalty_arrival_time_kwargs:
    b_0: 0
    b_1: null
  penalty_departure_time: polynomial
  penalty_departure_time_kwargs:
    b_0: 0
    b_1: null
  penalty_cost: polynomial
  penalty_cost_kwargs:
    b_0: 0
    b_1: null
  penalty_travel_time: polynomial
  penalty_travel_time_kwargs:
    b_0: 0
    b_1: null
  error: norm
  error_kwargs: null
- id: 6
  name: Leisure2
  arrival_time: norm
  arrival_time_kwargs:
    loc: 17
    scale: null
  purchase_day: poisson
  purchase_day_kwargs:
    mu: 7
  forbidden_departure_hours:
    start: 0
    end: 4
  seats:
  - id: 1
    utility: null
  - id: 2
    utility: null
  - id: 3
    utility: null
  - id: 4
    utility: null
  - id: 5
    utility: null
  - id: 6
    utility: null
  - id: 7
    utility: null
  - id: 8
    utility: null
  - id: 9
    utility: null
  train_service_providers:
  - id: 1
    utility: null
  - id: 2
    utility: null
  - id: 3
    utility: null
  penalty_arrival_time: polynomial
  penalty_arrival_time_kwargs:
    b_0: 0
    b_1: null
  penalty_departure_time: polynomial
  penalty_departure_time_kwargs:
    b_0: 0
    b_1: null
  penalty_cost: polynomial
  penalty_cost_kwargs:
    b_0: 0
    b_1: null
  penalty_travel_time: polynomial
  penalty_travel_time_kwargs:
    b_0: 0
    b_1: null
  error: norm
  error_kwargs: null
demandPattern:
- id: 1
  name: Monday-Thursday
  markets:
  - market: 1
    potential_demand: randint
    potential_demand_kwargs:
      low: null
      high: null
    user_pattern_distribution:
    - id: 1
      percentage: null
    - id: 2
      percentage: null
    - id: 3
      percentage: null
    - id: 4
      percentage: null
    - id: 5
      percentage: null
    - id: 6
      percentage: null
  - market: 2
    potential_demand: randint
    potential_demand_kwargs:
      low: null
      high: null
    user_pattern_distribution:
    - id: 1
      percentage: null
    - id: 2
      percentage: null
    - id: 3
      percentage: null
    - id: 4
      percentage: null
    - id: 5
      percentage: null
    - id: 6
      percentage: null
  - market: 3
    potential_demand: randint
    potential_demand_kwargs:
      low: null
      high: null
    user_pattern_distribution:
    - id: 1
      percentage: null
    - id: 2
      percentage: null
    - id: 3
      percentage: null
    - id: 4
      percentage: null
    - id: 5
      percentage: null
    - id: 6
      percentage: null
  - market: 4
    potential_demand: randint
    potential_demand_kwargs:
      low: null
      high: null
    user_pattern_distribution:
    - id: 1
      percentage: null
    - id: 2
      percentage: null
    - id: 3
      percentage: null
    - id: 4
      percentage: null
    - id: 5
      percentage: null
    - id: 6
      percentage: null
  - market: 5
    potential_demand: randint
    potential_demand_kwargs:
      low: null
      high: null
    user_pattern_distribution:
    - id: 1
      percentage: null
    - id: 2
      percentage: null
    - id: 3
      percentage: null
    - id: 4
      percentage: null
    - id: 5
      percentage: null
    - id: 6
      percentage: null
  - market: 6
    potential_demand: randint
    potential_demand_kwargs:
      low: null
      high: null
    user_pattern_distribution:
    - id: 1
      percentage: null
    - id: 2
      percentage: null
    - id: 3
      percentage: null
    - id: 4
      percentage: null
    - id: 5
      percentage: null
    - id: 6
      percentage: null
- id: 2
  name: Friday-Saturday
  markets:
  - market: 1
    potential_demand: randint
    potential_demand_kwargs:
      low: null
      high: null
    user_pattern_distribution:
    - id: 1
      percentage: null
    - id: 2
      percentage: null
    - id: 3
      percentage: null
    - id: 4
      percentage: null
    - id: 5
      percentage: null
    - id: 6
      percentage: null
  - market: 2
    potential_demand: randint
    potential_demand_kwargs:
      low: null
      high: null
    user_pattern_distribution:
    - id: 1
      percentage: null
    - id: 2
      percentage: null
    - id: 3
      percentage: null
    - id: 4
      percentage: null
    - id: 5
      percentage: null
    - id: 6
      percentage: null
  - market: 3
    potential_demand: randint
    potential_demand_kwargs:
      low: null
      high: null
    user_pattern_distribution:
    - id: 1
      percentage: null
    - id: 2
      percentage: null
    - id: 3
      percentage: null
    - id: 4
      percentage: null
    - id: 5
      percentage: null
    - id: 6
      percentage: null
  - market: 4
    potential_demand: randint
    potential_demand_kwargs:
      low: null
      high: null
    user_pattern_distribution:
    - id: 1
      percentage: null
    - id: 2
      percentage: null
    - id: 3
      percentage: null
    - id: 4
      percentage: null
    - id: 5
      percentage: null
    - id: 6
      percentage: null
  - market: 5
    potential_demand: randint
    potential_demand_kwargs:
      low: null
      high: null
    user_pattern_distribution:
    - id: 1
      percentage: null
    - id: 2
      percentage: null
    - id: 3
      percentage: null
    - id: 4
      percentage: null
    - id: 5
      percentage: null
    - id: 6
      percentage: null
  - market: 6
    potential_demand: randint
    potential_demand_kwargs:
      low: null
      high: null
    user_pattern_distribution:
    - id: 1
      percentage: null
    - id: 2
      percentage: null
    - id: 3
      percentage: null
    - id: 4
      percentage: null
    - id: 5
      percentage: null
    - id: 6
      percentage: null
- id: 3
  name: Sunday
  markets:
  - market: 1
    potential_demand: randint
    potential_demand_kwargs:
      low: null
      high: null
    user_pattern_distribution:
    - id: 1
      percentage: null
    - id: 2
      percentage: null
    - id: 3
      percentage: null
    - id: 4
      percentage: null
    - id: 5
      percentage: null
    - id: 6
      percentage: null
  - market: 2
    potential_demand: randint
    potential_demand_kwargs:
      low: null
      high: null
    user_pattern_distribution:
    - id: 1
      percentage: null
    - id: 2
      percentage: null
    - id: 3
      percentage: null
    - id: 4
      percentage: null
    - id: 5
      percentage: null
    - id: 6
      percentage: null
  - market: 3
    potential_demand: randint
    potential_demand_kwargs:
      low: null
      high: null
    user_pattern_distribution:
    - id: 1
      percentage: null
    - id: 2
      percentage: null
    - id: 3
      percentage: null
    - id: 4
      percentage: null
    - id: 5
      percentage: null
    - id: 6
      percentage: null
  - market: 4
    potential_demand: randint
    potential_demand_kwargs:
      low: null
      high: null
    user_pattern_distribution:
    - id: 1
      percentage: null
    - id: 2
      percentage: null
    - id: 3
      percentage: null
    - id: 4
      percentage: null
    - id: 5
      percentage: null
    - id: 6
      percentage: null
  - market: 5
    potential_demand: randint
    potential_demand_kwargs:
      low: null
      high: null
    user_pattern_distribution:
    - id: 1
      percentage: null
    - id: 2
      percentage: null
    - id: 3
      percentage: null
    - id: 4
      percentage: null
    - id: 5
      percentage: null
    - id: 6
      percentage: null
  - market: 6
    potential_demand: randint
    potential_demand_kwargs:
      low: null
      high: null
    user_pattern_distribution:
    - id: 1
      percentage: null
    - id: 2
      percentage: null
    - id: 3
      percentage: null
    - id: 4
      percentage: null
    - id: 5
      percentage: null
    - id: 6
      percentage: null
day:
- id: 1
  date: 2025-11-02
  demandPattern: 3
- id: 2
  date: 2025-11-03
  demandPattern: 1
- id: 3
  date: 2025-11-04
  demandPattern: 1
- id: 4
  date: 2025-11-05
  demandPattern: 1
- id: 5
  date: 2025-11-06
  demandPattern: 1
- id: 6
  date: 2025-11-07
  demandPattern: 2
- id: 7
  date: 2025-11-08
  demandPattern: 2
